impedance_controller:
  type: force_controllers/ImpedanceController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  root_name: panda_link0
  tip_name: tool
  cartesian_stiffness:
    translation:
      - 10
      - 10
      - 10
    rotation:
      - 5
      - 5
      - 5
