impedance_controller:
  type: force_controllers/ImpedanceController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  root_name: world
  tip_name: tool
  cartesian_stiffness:
    translation:
      - 100
      - 100
      - 100
    rotation:
      - 50
      - 50
      - 50
  cartesian_damping:
    translation:
      - 65
      - 65
      - 65
    rotation:
      - 45
      - 45
      - 45
